name: lint
on: push

env:
  DOTNET_VERSION: '7.x'

jobs:
  run-lint-check-csharp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: pwd check
        run: |
          pwd
      - name: Lint Check
        run: |
          dotnet format --verify-no-changes battlePencil.csproj --include Assets/Scripts/
